// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM9SGZ-QYqeDbM0iU3Z4zBqMoP-xf7Ndw',
    appId: '1:434474254915:web:649d4f9ee8521b68264af6',
    messagingSenderId: '434474254915',
    projectId: 'efterskolementor-dk',
    authDomain: 'efterskolementor-dk.firebaseapp.com',
    storageBucket: 'efterskolementor-dk.appspot.com',
    measurementId: 'G-1CSSGL415E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdNFiZxjce6A1TqBKgWBehzPVj83g1A4Q',
    appId: '1:434474254915:android:932a15a571c25368264af6',
    messagingSenderId: '434474254915',
    projectId: 'efterskolementor-dk',
    storageBucket: 'efterskolementor-dk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTD2gLpRUv8hCa_FCz-x7rNPRlEGlZDGk',
    appId: '1:434474254915:ios:fcbb370ef9d257f1264af6',
    messagingSenderId: '434474254915',
    projectId: 'efterskolementor-dk',
    storageBucket: 'efterskolementor-dk.appspot.com',
    iosBundleId: 'com.example.efterskoleAdmin',
  );
}
